"""
Basic RC thermal model for the HVAC Digital Twin.
Person 01: Twin Engineer
"""

from dataclasses import dataclass


@dataclass
class ThermalParameters:
    """Parameters describing the thermal behavior of a room."""

    R: float
    C: float
    window_area_m2: float
    shading_coefficient: float = 0.5


def calculate_solar_heat_gain(
    solar_radiation_w_m2: float,
    window_area_m2: float,
    shading_coefficient: float,
) -> float:
    """
    Calculate solar heat gain.

    Q_solar = solar_radiation * window_area * shading_coefficient
    """
    return (
        solar_radiation_w_m2
        * window_area_m2
        * shading_coefficient
    )


def calculate_occupancy_heat_gain(
    occupancy_count: int,
    heat_per_person_w: float = 100.0,
) -> float:
    """
    Calculate heat generated by occupants.
    """

    return occupancy_count * heat_per_person_w


def calculate_next_temperature(
    indoor_temp_c: float,
    outdoor_temp_c: float,
    R: float,
    C: float,
    dt: float,
    q_solar_w: float = 0.0,
    q_occupancy_w: float = 0.0,
    q_hvac_w: float = 0.0,
) -> float:
    """
    Calculate next indoor temperature using Euler integration.

    C * dT/dt =
        (T_outdoor - T_indoor) / R
        + Q_solar
        + Q_occupancy
        + Q_hvac
    """

    heat_transfer = (
        (outdoor_temp_c - indoor_temp_c) / R
    )

    total_heat = (
        heat_transfer
        + q_solar_w
        + q_occupancy_w
        + q_hvac_w
    )

    temperature_change = dt * (total_heat / C)

    return indoor_temp_c + temperature_change
